### PR TITLE
Smarties API bootstrap

### PR DESCRIPTION
**Pull request by Jarek64**
Added smarties candy paths to web API. Added variables file for smarties candy data. Added gitignore file.

### CODE REVIEW

**Comment by jkunkee** [comment]
This is a pretty good PR description. I would add that the PR includes `.gitignore`, and I think the PR title could be more descriptive.

**Comment by Jarek64** [comment]
Updated comments and title with feedback from jkunkee.

**Comment by jkunkee** [comment]
Approved (because I can't figure out which button to press to change the Review status)

**Review by jkunkee — COMMENTED** [review]
LGTM

**Pull request merged**
